= AdminFaces
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:includedir: _includes
:experimental:

:projectRoot: ../../..

:link-adminfaces: http://github.com/adminfaces
:link-admin-showcase: {link-adminfaces}/admin-showcase
:link-admin-showcase-openshift: http://adminfaces-rpestano.rhcloud.com/showcase/
:link-admin-starter: {link-adminfaces}/admin-starter
:link-admin-template: {link-adminfaces}/admin-template
:link-admin-theme: {link-adminfaces}/admin-theme
:link-admin-designer: {link-adminfaces}/admin-designer
:link-admin-mobile: {link-adminfaces}/admin-mobile

:link-jsf: https://javaserverfaces.java.net/
:link-primefaces: http://primefaces.org
:link-bootstrap: http://getbootstrap.com/
:link-adminlte: https://almsaeedstudio.com/themes/AdminLTE/index2.html
:link-less: http://lesscss.org/


ifeval::["{backend}" == "html5"]
icon:file-pdf-o[] Read this documentation {link-admin-docs}/index.pdf[in PDF here, role="external", window="_blank"].
endif::[]

ifeval::["{backend}" == "pdf"]
icon:html5[] Read this documentation {link-admin-docs}/[in HTML5 here, role="external", window="_blank"].
endif::[]

== Introduction

{link-adminfaces}[AdminFaces] is an open source project which brings {link-bootstrap}[Bootstrap^] and {link-adminlte}[AdminLTE^] to your application via a {link-primefaces}[PrimeFaces^] theme and a {link-jsf}[JSF^] `responsive` template.

AdminFaces ecosystem is composed by the following projects:

* {link-admin-theme}[Admin Theme^]: A Primefaces theme based on {link-bootstrap}[Bootstrap^] and {link-adminlte}[Admin LTE^] where {link-primefaces}[Primefaces^] components are customized to look like mentioned frameworks.
* {link-admin-template}[Admin Template^]: A *fully responsive* {link-jsf}[Java Server Faces^] `admin` template (used by this Showcase) which is also based on *Bootstrap* and *Admin LTE*.
* {link-admin-showcase}[Admin Showcase^]: A showcase web application, {link-admin-showcase-openshift}[deployed on openshift^], which demonstrates AdminFaces main features and components.
* {link-admin-designer}[Admin Designer^]: The same showcase application with Admin Theme and Admin Template bundled (instead of being library dependencies) in order to make it easier to customize the theme and the template.
* {link-admin-starter}[Admin Starter^]: A simple starter project to get you started with AdminFaces.
* {link-admin-mobile}[Admin Mobile^]: A simple https://developer.android.com/studio/index.html[Android Studio^] project which uses https://developer.android.com/reference/android/webkit/WebView.html[Webview^] to create an https://www.mobiloud.com/blog/native-web-or-hybrid-apps/[hybrid web app^] based on Admin Showcase.

In subsequent chapters we will drive through each project in detail.

include::{includedir}/01-theme.adoc[leveloffset=+1]

include::{includedir}/02-template.adoc[leveloffset=+1]

include::{includedir}/03-designer.adoc[leveloffset=+1]

include::{includedir}/04-starter.adoc[leveloffset=+1]

include::{includedir}/05-mobile.adoc[leveloffset=+1]
