= AdminFaces
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:experimental:



:link-adminfaces: http://github.com/adminfaces/
:link-admin-showcase: {link-adminfaces}/admin-showcase
:link-admin-showcase-openshift: http://adminfaces-rpestano.rhcloud.com/showcase/
:link-admin-starter: {link-adminfaces}/admin-starter
:link-admin-template: {link-adminfaces}/admin-template
:link-admin-theme: {link-adminfaces}/admin-theme
:link-admin-designer: {link-adminfaces}/admin-designer

:link-jsf: https://javaserverfaces.java.net/
:link-primefaces: http://primefaces.org
:link-bootstrap: http://getbootstrap.com/
:link-adminlte: https://almsaeedstudio.com/themes/AdminLTE/index2.html


ifeval::["{backend}" == "html5"]
icon:file-pdf-o[] Read this documentation {link-admin-docs}/index.pdf[in PDF here, role="external", window="_blank"].
endif::[]

ifeval::["{backend}" == "pdf"]
icon:html5[] Read this documentation {link-admin-docs}/[in HTML5 here, role="external", window="_blank"].
endif::[]

== Introduction

{link-adminfaces}[AdminFaces] is an open source project which brings {link-bootstrap}[Bootstrap^] and {link-adminlte}[AdminLTE^] to your application via {link-primefaces}[Primefaces^] theme and {link-jsf}[JSF^] `responsive` template.

AdminFaces ecosystem is composed by following projects:

* {link-admin-theme}[Admin Theme^]: Is a Primefaces theme based on {link-bootstrap}[Bootstrap^] and {link-adminlte}[Admin LTE^] where {link-primefaces}[Primefaces^] components are customized to look like mentioned frameworks.
* {link-admin-template}[Admin Template^]: It's a *fully responsive* {link-jsf}[Java Server Faces^] `admin` template (used by this Showcase) which is also based on *Bootstrap* and *Admin LTE*.
* {link-admin-showcase}[Admin Showcase^]: A showcase web application which demonstrates AdminFaces main features and components.
* {link-admin-designer}[Admin Designer^]: It's the same showcase application with Admin Theme and Admin Template bundled (instead of being library dependencies) in order to make it easier to customize the theme and the template.
* {link-admin-starter}[Admin Starter^]: A simple starter project to get you started with AdminFaces.
